### PR TITLE
BanditPAM v4.0.2

### LINKED ISSUE #227: Don't perform any swaps if k=1

### LINKED ISSUE #228: FastPAM1 is broken
Takes very long with `k=5` on MNIST-1k

### LINKED ISSUE #232: Change `exact` in `buildTarget` and `swapTarget` to bool

### LINKED ISSUE #234: Implement `buildLoss` function

### LINKED ISSUE #242: pip install on windows doesn't use MS Visual C++ compiler
In the Windows Python world the MS Visual C++ compiler is definitely the default compiler used and also the one used to compile the official Python distribution. It should be supported by default.

```
Exception: No C++ compiler was found. Please install LLVM clang.
```

### LINKED ISSUE #250: New error in GHA
`--no-use-pep517 error: It is not possible to use --no-use-pep517
without setuptools and wheel installed.`

### PR DESCRIPTION
**Pull request by Adarsh321123**
BanditPAM `v4.0.2` contains the following changes:

**Organization and Functionality:**
- We include the files, edits, and instructions to succeed in the CMake and Python builds on Windows, Mac, and Linux.
- Note that `carma` has now bumped to [version v0.6.7](https://github.com/RUrlus/carma/commit/8405bafc40b1bf06795e7004c7898a08963b688c).
- Does not require LLVM's clang when running `pip install .` (Fixes #242)
- Swaps are only performed in `banditpam.cpp`, `banditpam_orig.cpp`, `fastpam1.cpp`, and `pam.cpp` if k=1 (Fixes #227)
- Uses `bool` data type when necessary (Fixes #232)
- Implements the `buildLoss` functionality (Fixes #234)
- Modifies the FastPAM1 implementation such that the runtime is significantly reduced while resulting in the same medoids (Fixes #228)
- Ensures Linux GHA error does not appear anymore (Fixes #250)
- Update GHAs to use `python -m pip` throughout instead of just `pip`
- Mac GHAs now run on `macos-latest` as `macos-10.15` is now unsupported.
- Fixes failing GHAs that activated on PR.

**Tests:**
- Updated incorrect assertion in `tests/test_initialization.py`

**Style:**
- Ran `black`, `flake8`, a combination of `clang-format` and `cpplint`, and our own style definitions over codebase (such as using 2 spaces instead of 4 in C++ code).

**Documentation:**
- Documented functional CMake and Python builds on Windows.

### CODE REVIEW

File: src/python_bindings/kmedoids_pywrapper.cpp [hunk 1]
```diff
@@ -16,27 +16,36 @@
...
-  // Module functions
-  m.doc() = "BanditPAM Python library, implemented in C++";
-  m.attr("__version__") = VERSION_INFO;
-  m.def("get_max_threads",  // TODO(@motiwari): change to get_num_threads
+    PYBIND11_MODULE(banditpam, m
+    ) {
+    // Module functions
+    m.
+
+    doc() = "BanditPAM Python library, implemented in C++";
```
Comment (motiwari) [inline src/python_bindings/kmedoids_pywrapper.cpp:24]: ??

File: src/python_bindings/kmedoids_pywrapper.cpp [hunk 2]
```diff
@@ -16,27 +16,36 @@
...
+    // Constructor
+    // NOTE: The order of these matters! Otherwise you can get warnings about
+    //  variables not being intialized in the same order as their declarations,
+    //  which can lead to undefined behavior (variables being intialized with
+    //  each others' values). The order here much also match that of the
+    //  constructor in kmedoids_algorithm.*pp
+    cls.
+
+    def(
     pybind11::init<int, std::string, int, int, int, bool, bool, int, bool>(),
```
Comment (motiwari) [inline src/python_bindings/kmedoids_pywrapper.cpp:45]: ??

File: setup.py [hunk 3]
```diff
@@ -483,40 +550,52 @@ def main():
...
+                        os.getcwd(),
+                        r"headers\armadillo\examples\lib_win64"
+                        + r"\libopenblas.dll",
+                    )
+                ],
+            ),
+        ]
+    else:
+        my_data_files = [("docs", [os.path.join("docs", "long_desc.rst")])]
+
```
Comment (motiwari) [inline setup.py:598]: The first data file is common to all platforms, so you can initialize `my_data_files` to that and `append` if on `win32`

File: setup.py [hunk 4]
```diff
@@ -94,6 +100,8 @@ def cpp_flag(compiler: str):
     compiler_name = compiler_check()
     if compiler_name == "clang":
         flags = ["-std=c++17", "-std=c++14", "-std=c++11"]
+    elif compiler_name == "msvc":
+        flags = ["/std:c++17"]
```
Comment (motiwari) [inline setup.py:104]: Add comment that this is required for `std::optional`

File: setup.py [hunk 5]
```diff
@@ -94,6 +100,8 @@ def cpp_flag(compiler: str):
     compiler_name = compiler_check()
     if compiler_name == "clang":
         flags = ["-std=c++17", "-std=c++14", "-std=c++11"]
```
Comment (motiwari) [inline setup.py:102]: C++14 and C++11 should be removed because we're using `std::optional`

File: setup.py [hunk 6]
```diff
@@ -363,6 +378,9 @@ class BuildExt(build_ext):
         linux_opts = ["-O3"]
         c_opts["unix"] += linux_opts
         l_opts["unix"] += linux_opts
+    elif sys.platform == "win32":
+        windows_opts = ["/fsanitize=address"]
```
Comment (motiwari) [inline setup.py:382]: Add comment that this is currently necessary for reasons we don't understand

File: setup.py [hunk 7]
```diff
@@ -363,6 +378,9 @@ class BuildExt(build_ext):
...
+        c_opts["msvc"] += windows_opts
```
Comment (motiwari) [inline setup.py:383]: Looks unnecessary to use `windows_opts` temp variable, can assign `c_opts["msvc"]` directly

File: setup.py [hunk 8]
```diff
@@ -448,32 +470,77 @@ def main():
...
+                "/", "usr", "local", "Cellar", "libomp", "15.0.2", "include"
+            ),
             # for macos-latest
-            os.path.join("/", "usr", "local", "Cellar", "libomp",
-                         "15.0.7", "include"),
+            os.path.join(
+                "/", "usr", "local", "Cellar", "libomp", "15.0.7", "include"
+            ),
+        ]
+    else:  # WIN32
```
Comment (motiwari) [inline setup.py:490]: Make this an explicit `elif` check for Windows, and add a new `else` that throws an `Exception("Unrecognized platform")`

**Review by motiwari — CHANGES_REQUESTED** [review]
Great work getting this to work on Windows -- this is monumental!

General changes needed:
- Can you set the C++ code formatter to use 2 spaces instead of 4? There's too much whitespace right now (and 2 spaces is in line with Google style guides)
- Please self-review the whole PR
- update PR message according to release instructions
- In future PRs, style refactors should be an entirely standalone PR (otherwise it's hard to tell if functionality was also changed when you're making style changes)
- Future PRs should be smaller for easier review

General feedback:
- Use more comments!

File: .github/workflows/run_cmake_build.yml [hunk 9]
```diff
@@ -38,6 +38,14 @@ jobs:
           mkdir -p data
           curl -XGET https://motiwari.com/banditpam_data/MNIST_1k.csv > data/MNIST_1k.csv
 
+      - name: Clone for PR
+        if: ${{ github.event_name == 'pull_request' }}
+        run: git clone -b $GITHUB_HEAD_REF https://github.com/motiwari/BanditPAM
```
[the remark this answers is not in the document]
Comment (Adarsh321123) [reply .github/workflows/run_cmake_build.yml:43]: The below uses `{}` because of bash string manipulation to remove `refs/heads/` from `GITHUB_REF`, which isn't necessary here.

File: .github/workflows/run_linux_tests.yml [hunk 10]
```diff
@@ -76,9 +77,16 @@ jobs:
       #   run : |
       #     pytest tests/test_larger.py
 
+      - name: Clone for PR
+        if: ${{ github.event_name == 'pull_request' }}
+        run: git clone -b $GITHUB_HEAD_REF https://github.com/motiwari/BanditPAM
```
[the remark this answers is not in the document]
Comment (Adarsh321123) [reply .github/workflows/run_linux_tests.yml:82]: Please see response above

File: docs/install_windows.md [hunk 11]
```diff
@@ -1,38 +1,33 @@
...
 ## Prerequisites
 Please ensure the following dependencies are installed:
- - A C++ compiler; we recommend LLVM's `clang`: via the [LLVM installation instructions](https://clang.llvm.org/get_started.html)
- - OpenMP: if using LLVM's `clang`, then OpenMP is already enabled
- - `CMake`: via the [CMake installation instructions](https://cmake.org/install/)
- - Armadillo: via the [Armadillo installation instructions](http://arma.sourceforge.net/download.html)
+ - Visual Studio (2022 is recommended) with "Desktop development with C++" workload: via the [Visual Studio download page](https://visualstudio.microsoft.com/vs/)
+ - The Armadillo library: via `git clone https://gitlab.com/conradsnicta/armadillo-code.git armadillo` in the `headers` directory
  - CARMA: via the instructions in [its guide](https://github.com/RUrlus/carma#installation)
  - Python3: if not installed, we recommend installing Python3 via [Anaconda](https://www.anaconda.com/products/individual), which is CPython compiled with `clang`
```
[the remark this answers is not in the document]
Comment (Adarsh321123) [reply docs/install_windows.md:10]: It's not clear from Googling so I will remove ", which is CPython compiled with `clang`"

File: docs/install_windows.md [hunk 12]
```diff
@@ -1,38 +1,33 @@
...
-```
-
-Do not attempt to compile the BanditPAM extension with `gcc` if your Python used `clang`, and vice versa.
 
 ## BanditPAM Installation
 
-BanditPAM can then be installed via one of the following ways:
-1) Running `pip install banditpam`, OR
-2) Running `pip install .` in the home directory (`/BanditPAM`)
+Copy the files in [this repo](https://github.com/ThrunGroup/BanditPAM-Windows) into the following locations:
```
[the remark this answers is not in the document]
Comment (Adarsh321123) [reply docs/install_windows.md:16]: Done!: https://github.com/ThrunGroup/BanditPAM_Windows/tree/main

File: docs/install_windows.md [hunk 13]
```diff
@@ -1,38 +1,33 @@
...
-The following is a list of issues seen when installing BanditPAM on Windows. To report a bug, please file an issue at https://github.com/motiwari/BanditPAM/
+CMake Build:
+1) Add the Visual Studio IDE location to PATH in Environment Variables (e.g. `C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE`).
+2) Add `${project_dir}\headers\armadillo\examples\lib_win64` to PATH 
+3) Run `devenv BanditPAM.sln /Build "Release|x64"` after `cmake ..` in a prompt other than Git Bash
+4) The `.exe` will be located in `build/src/Release`
 
-- You may run into an error like `error: ‘class arma::Mat<float>’ has no member named ‘n_alloc’`; this is fundamentally due to an [error in CARMA](https://github.com/RUrlus/carma/pull/98). If this isn't fixed by the time you're reading this, follow the fix described in [this issue](https://github.com/motiwari/BanditPAM/issues/169).
+Python Build:
+1) Add the location of `cl.exe` to PATH in Environment Variables (e.g. `C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64`).
```
[the remark this answers is not in the document]
Comment (Adarsh321123) [reply docs/install_windows.md:28]: Yes because that is where `compiler_check()` in `setup.py` will look for MSVC. Please let me know if you think otherwise.

File: docs/install_windows.md [hunk 14]
```diff
@@ -1,38 +1,33 @@
...
+1) Run `python -m pip install banditpam`, OR
+2) Follow these steps:
+   3) Run `python -m pip install .` in the home directory (`/BanditPAM`)
```
[the remark this answers is not in the document]
Comment (Adarsh321123) [reply docs/install_windows.md:31]: As mentioned in Slack, it's necessary for the user to install, add the ASan dependency, and then install again for the Windows Python build to work, so this shouldn't be deleted.

File: src/CMakeLists.txt [hunk 15]
```diff
@@ -3,24 +3,52 @@ include_directories(${PROJECT_SOURCE_DIR}/headers/algorithms)
 include_directories(${PROJECT_SOURCE_DIR}/headers/python_bindings)
 include_directories(${PROJECT_SOURCE_DIR}/headers/carma/include)
 include_directories(${PROJECT_SOURCE_DIR}/headers/carma/include/carma_bits)
+# Include directory for windows
+if(WIN32)
+include_directories(${PROJECT_SOURCE_DIR}/headers/armadillo/include)
+include_directories(
+        ${PROJECT_SOURCE_DIR}/headers/armadillo/include/armadillo_bits)
+set(OPENBLAS_dir ${PROJECT_SOURCE_DIR}/headers/armadillo/examples/lib_win64)
```
[the remark this answers is not in the document]
Comment (Adarsh321123) [reply src/CMakeLists.txt:11]: According to `cmake-lint` (which I ran using `cmake-lint src/CMakeLists.txt`), we should not indent inside `if` blocks. Please let me know if you think otherwise.

File: src/CMakeLists.txt [hunk 16]
```diff
@@ -3,24 +3,52 @@ include_directories(${PROJECT_SOURCE_DIR}/headers/algorithms)
...
+# For Mac Github Runner to find OpenMP -- potentially unnecessary after fixing
+# -Xpreprocessor -fopenmp issue
+if(APPLE OR UNIX)
 include_directories(/usr/local/Cellar/libomp/15.0.2/include)
 include_directories(/usr/local/Cellar/libomp/15.0.7/include)
 include_directories(/usr/local/Cellar/libomp)
+include_directories(/usr/local/opt/libomp/include)
 include_directories(/usr/local/opt/libomp/lib)
 include_directories(/usr/local/opt/libomp)
 include_directories(/usr/local/opt)
```
[the remark this answers is not in the document]
Comment (Adarsh321123) [reply src/CMakeLists.txt:23]: Ditto

File: src/CMakeLists.txt [hunk 17]
```diff
@@ -3,24 +3,52 @@ include_directories(${PROJECT_SOURCE_DIR}/headers/algorithms)
...
+endif()
 
-add_executable(BanditPAM main.cpp)
+if(WIN32)
+add_executable(BanditPAM getopt.cpp main.cpp )
```
[the remark this answers is not in the document]
Comment (Adarsh321123) [reply src/CMakeLists.txt:27]: Please see comment above about `cmake-lint`.

File: src/CMakeLists.txt [hunk 18]
```diff
@@ -3,24 +3,52 @@ include_directories(${PROJECT_SOURCE_DIR}/headers/algorithms)
...
+
+elseif(APPLE OR UNIX)
+add_executable(BanditPAM main.cpp )
```
[the remark this answers is not in the document]
Comment (Adarsh321123) [reply src/CMakeLists.txt:30]: Please see comment above about `cmake-lint`.

File: src/CMakeLists.txt [hunk 19]
```diff
@@ -3,24 +3,52 @@ include_directories(${PROJECT_SOURCE_DIR}/headers/algorithms)
...
+include_directories(/usr/local/opt/libomp/include)
 include_directories(/usr/local/opt/libomp/lib)
 include_directories(/usr/local/opt/libomp)
 include_directories(/usr/local/opt)
+endif()
 
-add_executable(BanditPAM main.cpp)
+if(WIN32)
+add_executable(BanditPAM getopt.cpp main.cpp )
+
```
[the remark this answers is not in the document]
Comment (Adarsh321123) [reply src/CMakeLists.txt:28]: This is necessary for the CMake build. Otherwise, we get this:

```
3>------ Build started: Project: BanditPAM, Configuration: Release x64 ------
3>Building Custom Rule C:/impt/CLionTest/BanditPAM/src/CMakeLists.txt
3>cl : command line  warning D9002: ignoring unknown option '-O3'
3>main.cpp
3>main.obj : error LNK2019: unresolved external symbol getopt referenced in function main
3>main.obj : error LNK2019: unresolved external symbol optarg referenced in function main
3>main.obj : error LNK2019: unresolved external symbol optind referenced in function main
3>main.obj : error LNK2019: unresolved external symbol optopt referenced in function main
3>C:\impt\CLionTest\BanditPAM\build\src\Release\BanditPAM.exe : fatal error LNK1120: 4 unresolved externals
3>Done building project "BanditPAM.vcxproj" -- FAILED.
4>------ Skipped Build: Project: ALL_BUILD, Configuration: Release x64 ------
4>Project not selected to build for this solution configuration
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 1 skipped ==========
========== Elapsed 00:11.257 ==========
.\BanditPAM : The term '.\BanditPAM' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\adars\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:11 char:43
+ function fresh { rebuild; cd src/Release; .\BanditPAM -f ../../../dat ...
+                                           ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\BanditPAM:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

File: src/CMakeLists.txt [hunk 20]
```diff
@@ -3,24 +3,52 @@ include_directories(${PROJECT_SOURCE_DIR}/headers/algorithms)
...
 
-add_library(BanditPAM_LIB algorithms/kmedoids_algorithm.cpp algorithms/pam.cpp algorithms/banditpam.cpp algorithms/banditpam_orig.cpp algorithms/fastpam1.cpp)
 target_link_libraries(BanditPAM PUBLIC BanditPAM_LIB)
 
-find_package(OpenMP REQUIRED)
-target_link_libraries(BanditPAM_LIB PUBLIC OpenMP::OpenMP_CXX)
-target_link_libraries(BanditPAM PUBLIC OpenMP::OpenMP_CXX)
+if(WIN32)
+target_link_directories(BanditPAM PUBLIC ${OPENBLAS_dir})
+target_link_libraries(BanditPAM_LIB libopenblas)
```
[the remark this answers is not in the document]
Comment (Adarsh321123) [reply src/CMakeLists.txt:41]: Please see comment above about `cmake-lint`.

File: src/CMakeLists.txt [hunk 21]
```diff
@@ -3,24 +3,52 @@ include_directories(${PROJECT_SOURCE_DIR}/headers/algorithms)
...
+        BanditPAM_LIB algorithms/kmedoids_algorithm.cpp algorithms/pam.cpp
+        algorithms/banditpam.cpp algorithms/banditpam_orig.cpp
+        algorithms/fastpam1.cpp)
 
-add_library(BanditPAM_LIB algorithms/kmedoids_algorithm.cpp algorithms/pam.cpp algorithms/banditpam.cpp algorithms/banditpam_orig.cpp algorithms/fastpam1.cpp)
 target_link_libraries(BanditPAM PUBLIC BanditPAM_LIB)
 
-find_package(OpenMP REQUIRED)
-target_link_libraries(BanditPAM_LIB PUBLIC OpenMP::OpenMP_CXX)
-target_link_libraries(BanditPAM PUBLIC OpenMP::OpenMP_CXX)
```
[the remark this answers is not in the document]
Comment (Adarsh321123) [reply src/CMakeLists.txt:22]: OpenMP is already added to the compiler by default in UNIX. It is also already added to APPLE if the user uses LLVM's clang as it says in doc instructions. Please let me know if you would still like me to include these lines.

File: src/CMakeLists.txt [hunk 22]
```diff
@@ -3,24 +3,52 @@ include_directories(${PROJECT_SOURCE_DIR}/headers/algorithms)
...
+if(WIN32)
+target_link_directories(BanditPAM PUBLIC ${OPENBLAS_dir})
+target_link_libraries(BanditPAM_LIB libopenblas)
+endif()
 
+if(UNIX OR APPLE)
 find_package(Armadillo REQUIRED)
 include_directories(${ARMADILLO_INCLUDE_DIRS})
 target_link_libraries(BanditPAM PUBLIC ${ARMADILLO_LIBRARIES})
```
[the remark this answers is not in the document]
Comment (Adarsh321123) [reply src/CMakeLists.txt:47]: Please see comment above about `cmake-lint`.

File: src/CMakeLists.txt [hunk 23]
```diff
@@ -3,24 +3,52 @@ include_directories(${PROJECT_SOURCE_DIR}/headers/algorithms)
...
+endif()
+
+if(WIN32)
+string(REPLACE "/" "\\"  OPENBLAS_dir_win ${OPENBLAS_dir})
+add_custom_command(TARGET BanditPAM_LIB POST_BUILD
+            COMMAND copy ${OPENBLAS_dir_win}\\*.dll $(OutDir))
```
[the remark this answers is not in the document]
Comment (Adarsh321123) [reply src/CMakeLists.txt:53]: Please see comment above about `cmake-lint`.

File: src/algorithms/banditpam_orig.cpp [hunk 24]
```diff
@@ -13,501 +13,508 @@
...
+                permutationIdx = 0;
+            }
+            // inclusive of both indices
+            referencePoints = permutation.subvec(
+                    permutationIdx,
+                    permutationIdx + tmpBatchSize - 1);
+            permutationIdx += tmpBatchSize;
         } else {
-          sample(j) = (*bestDistances)(referencePoints(j));
+            referencePoints = arma::randperm(N, tmpBatchSize);
```
[the remark this answers is not in the document]
Comment (Adarsh321123) [reply src/algorithms/banditpam_orig.cpp:136]: I think GitHub got confused. Here's what happened:
- I initially added `clang-format` to replace `cpplint`.
- However, we decided to revert back to `cpplint` for this release.
- The combination of the above led to lines being moved around the file, so although both lines still exist in `banditpam_orig.cpp`, GitHub thought that I replaced one with the other.
- In the next release, I will add `clang-format` back to standardize the style across the source and header files.

File: src/algorithms/banditpam_orig.cpp [hunk 25]
```diff
@@ -13,501 +13,508 @@
...
+                permutationIdx = 0;
+            }
+            // inclusive of both indices
+            referencePoints = permutation.subvec(
+                    permutationIdx,
+                    permutationIdx + batchSize - 1);
+            permutationIdx += batchSize;
         } else {
-          total += (*secondBestDistances)(referencePoints(j));
+            referencePoints = arma::randperm(N, batchSize);
```
[the remark this answers is not in the document]
Comment (Adarsh321123) [reply src/algorithms/banditpam_orig.cpp:287]: Ditto

File: src/algorithms/banditpam_orig.cpp [hunk 26]
```diff
@@ -13,501 +13,508 @@
...
+                    } else {
+                        sample(j) = (*bestDistances)(referencePoints(j));
+                    }
+                }
+                sample(j) -= (*bestDistances)(referencePoints(j));
+            }
+            updated_sigma(k, n) = arma::stddev(sample);
         }
-      }
-      total -= (*bestDistances)(referencePoints(j));
```
[the remark this answers is not in the document]
Comment (Adarsh321123) [reply src/algorithms/banditpam_orig.cpp:379]: Ditto

File: src/python_bindings/kmedoids_pywrapper.cpp (hunk 1 above)
Comment (Adarsh321123) [reply src/python_bindings/kmedoids_pywrapper.cpp:24]: This is due to the `clang-format` and `cpplint` stuff mentioned above. The functionality still remains the same; only the style has changed. This will be fixed in the next release.

File: src/python_bindings/kmedoids_pywrapper.cpp (hunk 2 above)
Comment (Adarsh321123) [reply src/python_bindings/kmedoids_pywrapper.cpp:45]: Ditto

File: src/CMakeLists.txt (hunk 21 above)
[the remark this answers is not in the document]
Comment (Adarsh321123) [reply src/CMakeLists.txt:22]: Wall clock time is the same on my Mac with and without these lines

File: cmake-build-debug/.cmake/api/v1/query/cache-v2
Comment (motiwari) [inline cmake-build-debug/.cmake/api/v1/query/cache-v2:1]: delete

File: cmake-build-debug/.cmake/api/v1/query/cmakeFiles-v1
Comment (motiwari) [inline cmake-build-debug/.cmake/api/v1/query/cmakeFiles-v1:1]: delete

File: cmake-build-debug/.cmake/api/v1/query/codemodel-v2
Comment (motiwari) [inline cmake-build-debug/.cmake/api/v1/query/codemodel-v2:1]: delete

File: cmake-build-debug/.cmake/api/v1/query/toolchains-v1
Comment (motiwari) [inline cmake-build-debug/.cmake/api/v1/query/toolchains-v1:1]: delete

File: cmake-build-debug/.cmake/api/v1/reply/cache-v2-64bd7ec19a099ed68d96.json
Comment (motiwari) [inline cmake-build-debug/.cmake/api/v1/reply/cache-v2-64bd7ec19a099ed68d96.json:1]: delete

File: cmake-build-debug/.cmake/api/v1/reply/cmakeFiles-v1-ccacbba07b8dbad98135.json
Comment (motiwari) [inline cmake-build-debug/.cmake/api/v1/reply/cmakeFiles-v1-ccacbba07b8dbad98135.json:1]: delete

File: cmake-build-debug/.cmake/api/v1/reply/codemodel-v2-73a01eb8920c5505cf1f.json
Comment (motiwari) [inline cmake-build-debug/.cmake/api/v1/reply/codemodel-v2-73a01eb8920c5505cf1f.json:1]: delete

File: cmake-build-debug/.cmake/api/v1/reply/directory-.-Release-d0094a50bb2071803777.json
Comment (motiwari) [inline cmake-build-debug/.cmake/api/v1/reply/directory-.-Release-d0094a50bb2071803777.json:1]: delete

File: cmake-build-debug/.cmake/api/v1/reply/directory-src-Release-c94b7c2814d5a21df52c.json
Comment (motiwari) [inline cmake-build-debug/.cmake/api/v1/reply/directory-src-Release-c94b7c2814d5a21df52c.json:1]: delete

File: cmake-build-debug/.cmake/api/v1/reply/index-2023-06-13T18-31-39-0288.json
Comment (motiwari) [inline cmake-build-debug/.cmake/api/v1/reply/index-2023-06-13T18-31-39-0288.json:1]: delete

File: cmake-build-debug/.cmake/api/v1/reply/target-BanditPAM-Release-1411b852e3ae47f19ad2.json
Comment (motiwari) [inline cmake-build-debug/.cmake/api/v1/reply/target-BanditPAM-Release-1411b852e3ae47f19ad2.json:1]: delete

File: cmake-build-debug/.cmake/api/v1/reply/target-BanditPAM_LIB-Release-9b6d15a07f8e002eb22d.json
Comment (motiwari) [inline cmake-build-debug/.cmake/api/v1/reply/target-BanditPAM_LIB-Release-9b6d15a07f8e002eb22d.json:1]: delete

File: cmake-build-debug/.cmake/api/v1/reply/toolchains-v1-9476466ef080417a24a1.json
Comment (motiwari) [inline cmake-build-debug/.cmake/api/v1/reply/toolchains-v1-9476466ef080417a24a1.json:1]: delete

File: cmake-build-debug/CMakeCache.txt
Comment (motiwari) [inline cmake-build-debug/CMakeCache.txt:1]: delete

File: cmake-build-debug/CMakeFiles/3.24.2/CMakeCXXCompiler.cmake
Comment (motiwari) [inline cmake-build-debug/CMakeFiles/3.24.2/CMakeCXXCompiler.cmake:1]: delete

**Review by motiwari — APPROVED** [review]
LOOKS GREAT! Don't forget to make TestPyPI -> PyPI changes in the GHAs before merge (and verify that the GHA are succeeding on the push before merge)

**Comment by Adarsh321123** [comment]
Will do! I disabled all GHAs except for building the Linux and Mac wheels for the most recent push, so I will check that the GHAs succeed before then!
